# Generated by Django 5.0.7 on 2024-07-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Учится "),
        ),
    ]
