# Generated by Django 5.0.7 on 2024-07-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_category_product_delete_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="manufactured_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
