# Generated by Django 5.0.7 on 2024-07-30 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_category_product_delete_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image_previews",
            field=models.ImageField(
                blank=True, null=True, upload_to="products/", verbose_name="Превью"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="catalog.category",
                verbose_name="Категория",
            ),
        ),
    ]
