# Generated by Django 5.0.7 on 2024-08-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_alter_blogpost_options_alter_blogpost_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="published",
            field=models.BooleanField(default=True, verbose_name="Отображать на сайте"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="slug",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                unique=True,
                verbose_name="Slug_url",
            ),
        ),
    ]
