# Generated by Django 5.0.7 on 2024-08-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_alter_blogpost_published_alter_blogpost_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="slug",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Slug_url"
            ),
        ),
    ]
